name: Create buildartifacts zip
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
      - 'buildartifacts/scripts/**'


jobs:
  build:
    # Job name
    name: build zip job
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Create target dir to hold zip file
      # because "upload artifact v1" action takes a dir as input not a single file
      # - name: build zip steps
      - uses: actions/checkout@v1
      - run: mkdir buildartifacts-zip
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./buildartifacts-zip/buildartifacts_scripts.zip ./buildartifacts/scripts
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: buildscripts
          path: buildartifacts-zip
 
